apiVersion: apps/v1
kind: Deployment
metadata:
  name: productstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productstore
  template:
    metadata:
      labels:
        app: productstore
    spec:
      containers:
        - name: productstore
          image: <your-dockerhub-or-azure-image-url>
          ports:
            - containerPort: 80
